# ex: set ro:
# DO NOT EDIT.
# generated by smc (http://smc.sourceforge.net/)
# from file : AppClass.sm

import statemap


class AppClassState(statemap.State):

    def Entry(self, fsm):
        pass

    def Exit(self, fsm):
        pass

    def Alpha(self, fsm):
        self.Default(fsm)

    def CloseBracket(self, fsm):
        self.Default(fsm)

    def Comma(self, fsm):
        self.Default(fsm)

    def Digit(self, fsm):
        self.Default(fsm)

    def EOS(self, fsm):
        self.Default(fsm)

    def OpenBracket(self, fsm):
        self.Default(fsm)

    def Semicolon(self, fsm):
        self.Default(fsm)

    def Type(self, fsm):
        self.Default(fsm)

    def WhiteSpace(self, fsm):
        self.Default(fsm)

    def Default(self, fsm):
        msg = "\n\tState: %s\n\tTransition: %s" % (
            fsm.getState().getName(), fsm.getTransition())
        raise statemap.TransitionUndefinedException(msg)

class Map1_Default(AppClassState):

    def Alpha(self, fsm):
        ctxt = fsm.getOwner()
        fsm.getState().Exit(fsm)
        fsm.clearState()
        try:
            ctxt.Unacceptable()
        finally:
            fsm.setState(Map1.Error)
            fsm.getState().Entry(fsm)


    def Digit(self, fsm):
        ctxt = fsm.getOwner()
        fsm.getState().Exit(fsm)
        fsm.clearState()
        try:
            ctxt.Unacceptable()
        finally:
            fsm.setState(Map1.Error)
            fsm.getState().Entry(fsm)


    def Comma(self, fsm):
        ctxt = fsm.getOwner()
        fsm.getState().Exit(fsm)
        fsm.clearState()
        try:
            ctxt.Unacceptable()
        finally:
            fsm.setState(Map1.Error)
            fsm.getState().Entry(fsm)


    def OpenBracket(self, fsm):
        ctxt = fsm.getOwner()
        fsm.getState().Exit(fsm)
        fsm.clearState()
        try:
            ctxt.Unacceptable()
        finally:
            fsm.setState(Map1.Error)
            fsm.getState().Entry(fsm)


    def CloseBracket(self, fsm):
        ctxt = fsm.getOwner()
        fsm.getState().Exit(fsm)
        fsm.clearState()
        try:
            ctxt.Unacceptable()
        finally:
            fsm.setState(Map1.Error)
            fsm.getState().Entry(fsm)


    def WhiteSpace(self, fsm):
        ctxt = fsm.getOwner()
        fsm.getState().Exit(fsm)
        fsm.clearState()
        try:
            ctxt.Unacceptable()
        finally:
            fsm.setState(Map1.Error)
            fsm.getState().Entry(fsm)


    def Semicolon(self, fsm):
        ctxt = fsm.getOwner()
        fsm.getState().Exit(fsm)
        fsm.clearState()
        try:
            ctxt.Unacceptable()
        finally:
            fsm.setState(Map1.Error)
            fsm.getState().Entry(fsm)


    def Type(self, fsm):
        ctxt = fsm.getOwner()
        fsm.getState().Exit(fsm)
        fsm.clearState()
        try:
            ctxt.ClearSMC()
        finally:
            fsm.setState(Map1.Type)
            fsm.getState().Entry(fsm)


class Map1_Type(Map1_Default):

    def Alpha(self, fsm):
        ctxt = fsm.getOwner()
        if  ctxt.isValidType()  :
            fsm.getState().Exit(fsm)
            fsm.clearState()
            try:
                ctxt.CounterInc()
            finally:
                fsm.setState(Map1.Type)
                fsm.getState().Entry(fsm)
        else:
            Map1_Default.Alpha(self, fsm)
        
    def EOS(self, fsm):
        ctxt = fsm.getOwner()
        fsm.getState().Exit(fsm)
        fsm.clearState()
        try:
            ctxt.Acceptable()
        finally:
            fsm.setState(Map1.OK)
            fsm.getState().Entry(fsm)


    def WhiteSpace(self, fsm):
        ctxt = fsm.getOwner()
        if  ctxt.checkType()  :
            fsm.getState().Exit(fsm)
            fsm.clearState()
            try:
                ctxt.CounterZero()
                ctxt.clearSubstring()
            finally:
                fsm.setState(Map1.WhiteSpaces)
                fsm.getState().Entry(fsm)
        else:
            Map1_Default.WhiteSpace(self, fsm)
        
class Map1_WhiteSpaces(Map1_Default):

    def Alpha(self, fsm):
        ctxt = fsm.getOwner()
        fsm.getState().Exit(fsm)
        fsm.clearState()
        try:
            ctxt.CounterInc()
        finally:
            fsm.setState(Map1.Name)
            fsm.getState().Entry(fsm)


    def EOS(self, fsm):
        ctxt = fsm.getOwner()
        fsm.getState().Exit(fsm)
        fsm.clearState()
        try:
            ctxt.Acceptable()
        finally:
            fsm.setState(Map1.OK)
            fsm.getState().Entry(fsm)


    def WhiteSpace(self, fsm):
        fsm.getState().Exit(fsm)
        fsm.setState(Map1.WhiteSpaces)
        fsm.getState().Entry(fsm)


class Map1_Name(Map1_Default):

    def Alpha(self, fsm):
        ctxt = fsm.getOwner()
        if  ctxt.isValidName()  :
            fsm.getState().Exit(fsm)
            fsm.clearState()
            try:
                ctxt.CounterInc()
            finally:
                fsm.setState(Map1.Name)
                fsm.getState().Entry(fsm)
        else:
            Map1_Default.Alpha(self, fsm)
        
    def Digit(self, fsm):
        ctxt = fsm.getOwner()
        if  ctxt.isValidName()  :
            fsm.getState().Exit(fsm)
            fsm.clearState()
            try:
                ctxt.CounterInc()
            finally:
                fsm.setState(Map1.Name)
                fsm.getState().Entry(fsm)
        else:
            Map1_Default.Digit(self, fsm)
        
    def EOS(self, fsm):
        ctxt = fsm.getOwner()
        fsm.getState().Exit(fsm)
        fsm.clearState()
        try:
            ctxt.Acceptable()
        finally:
            fsm.setState(Map1.OK)
            fsm.getState().Entry(fsm)


class Map1_OK(Map1_Default):
    pass

class Map1_Error(Map1_Default):

    def EOS(self, fsm):
        ctxt = fsm.getOwner()
        endState = fsm.getState()
        fsm.clearState()
        try:
            ctxt.Unacceptable()
        finally:
            fsm.setState(endState)


class Map1(object):

    Type = Map1_Type('Map1.Type', 0)
    WhiteSpaces = Map1_WhiteSpaces('Map1.WhiteSpaces', 1)
    Name = Map1_Name('Map1.Name', 2)
    OK = Map1_OK('Map1.OK', 3)
    Error = Map1_Error('Map1.Error', 4)
    Default = Map1_Default('Map1.Default', -1)

class AppClass_sm(statemap.FSMContext):

    def __init__(self, owner):
        statemap.FSMContext.__init__(self, Map1.Type)
        self._owner = owner

    def __getattr__(self, attrib):
        def trans_sm(*arglist):
            self._transition = attrib
            getattr(self.getState(), attrib)(self, *arglist)
            self._transition = None
        return trans_sm

    def enterStartState(self):
        self._state.Entry(self)

    def getOwner(self):
        return self._owner

# Local variables:
#  buffer-read-only: t
# End:
